export interface PublicProject {
  id: string;
  projectId: string;
  projectName: string;
  category: string;
  sector: string;
  ministry: string;
  department: string;
  location: string;
  state: string;
  estimatedCost: number; // in crores
  expenditure: number; // in crores
  status: "ON_TRACK" | "UNDER_IMPLEMENTATION" | "COMPLETED" | "DELAYED" | "PLANNING";
  progress: number; // percentage 0-100
  startDate: string;
  expectedCompletion: string;
  image: string;
  description: string;
  highlights: string[];
  agency: string;
  aiRiskScore: "Low" | "Moderate" | "Optimal";
  videoUrl?: string;
  videoDuration?: string;
}

export interface VideoShowcaseItem {
  id: string;
  title: string;
  category: string;
  location: string;
  image: string;
  duration: string;
  currentTime: string;
  progressPercent: number;
  ministry: string;
  description: string;
}

export const HERO_VIDEO_ITEMS: VideoShowcaseItem[] = [
  {
    id: "delhi-mumbai-exp",
    title: "Delhi - Mumbai Greenfield Expressway",
    category: "Roads & Highways",
    location: "Haryana, Rajasthan, MP, Gujarat, Maharashtra",
    image: "/images/projects/expressway.jpg",
    duration: "1:30",
    currentTime: "0:45",
    progressPercent: 50,
    ministry: "Ministry of Road Transport and Highways",
    description: "1,386 km 8-lane access-controlled greenfield expressway reducing travel time between India's political and financial capitals to 12 hours.",
  },
  {
    id: "bullet-train-corridor",
    title: "Mumbai - Ahmedabad High Speed Rail Corridor",
    category: "Railways",
    location: "Maharashtra & Gujarat",
    image: "/images/projects/rail.jpg",
    duration: "2:15",
    currentTime: "1:08",
    progressPercent: 64,
    ministry: "Ministry of Railways",
    description: "India's first high-speed bullet train operating at 320 km/h with 12 stations, under-sea tunnels, and seismic warning systems.",
  },
  {
    id: "metro-expansion",
    title: "Phase-IV Urban Metro Mass Rapid Transit",
    category: "Urban Infrastructure",
    location: "NCR & Bengaluru",
    image: "/images/projects/metro.jpg",
    duration: "1:45",
    currentTime: "1:12",
    progressPercent: 81,
    ministry: "Ministry of Housing & Urban Affairs",
    description: "Driverless train operation (GoA 4) with integrated multimodal hubs connecting rail, bus terminals, and international airports.",
  },
  {
    id: "rewa-solar-park",
    title: "Ultra Mega Renewable Solar & Wind Park",
    category: "Energy",
    location: "Madhya Pradesh & Gujarat",
    image: "/images/projects/solar.jpg",
    duration: "1:50",
    currentTime: "0:58",
    progressPercent: 58,
    ministry: "Ministry of New & Renewable Energy",
    description: "Grid-parity clean energy generation supplying 750 MW green power to state utility grids and urban rapid transit systems.",
  },
  {
    id: "polavaram-dam",
    title: "National Multi-Purpose Irrigation & Hydel Mission",
    category: "Water & Irrigation",
    location: "Andhra Pradesh & Telangana",
    image: "/images/projects/water.jpg",
    duration: "2:05",
    currentTime: "1:22",
    progressPercent: 66,
    ministry: "Ministry of Jal Shakti",
    description: "Interlinking Godavari and Krishna rivers providing drinking water to 540 villages and generating 960 MW hydro-power.",
  },
  {
    id: "chenab-bridge",
    title: "Chenab River Railway Arch Bridge (USBRL)",
    category: "Railways & Bridges",
    location: "Jammu & Kashmir",
    image: "/images/projects/bridge.jpg",
    duration: "1:35",
    currentTime: "1:15",
    progressPercent: 95,
    ministry: "Ministry of Railways",
    description: "World's highest railway bridge at 359 m above river bed, engineered to withstand blast forces and Category-VIII seismic shocks.",
  },
];

export const PUBLIC_STATISTICS = {
  totalProjects: "1,248+",
  totalProjectsCount: 1248,
  activeProjects: "965",
  activeProjectsCount: 965,
  completedProjects: "283",
  completedProjectsCount: 283,
  totalBudget: "2,45,678 Cr",
  totalBudgetRaw: 245678,
  ministries: "36",
  ministriesCount: 36,
  statesUts: "28",
  statesUtsCount: 28,
  aiPoweredInsights: "Smart Insights",
  projectsUnderMonitoring: "1,248",
  activeSensors: "45,000+",
  droneSurveysCompleted: "8,420",
};

export const FEATURED_PROJECTS: PublicProject[] = [
  {
    id: "proj-1",
    projectId: "NHAI-DME-2023",
    projectName: "Delhi Mumbai Expressway",
    category: "Transport",
    sector: "Roads & Highways",
    ministry: "Ministry of Road Transport & Highways",
    department: "Department of Road Transport",
    agency: "National Highways Authority of India (NHAI)",
    location: "Delhi, Haryana, Rajasthan, MP, Gujarat, Maharashtra",
    state: "Multiple States",
    estimatedCost: 100000,
    expenditure: 72000,
    status: "ON_TRACK",
    progress: 72,
    startDate: "Mar 2019",
    expectedCompletion: "Dec 2026",
    image: "/images/projects/expressway.jpg",
    description: "The Delhi-Mumbai Expressway is a 1,386 km long, 8-lane wide access-controlled greenfield expressway connecting New Delhi with Mumbai.",
    highlights: [
      "Reduces travel duration from 24 hours to 12 hours",
      "Features animal overpasses and wildlife eco-ducts",
      "Dedicated corridor for EV fast charging lanes",
      "Fully digital optical fiber sensor network for speed and accident detection",
    ],
    aiRiskScore: "Optimal",
  },
  {
    id: "proj-2",
    projectId: "MAHSR-BULLET-2022",
    projectName: "High Speed Rail Corridor",
    category: "Railways",
    sector: "Railways",
    ministry: "Ministry of Railways",
    department: "Railway Board",
    agency: "National High Speed Rail Corporation Ltd (NHSRCL)",
    location: "Mumbai - Ahmedabad (508 km)",
    state: "Gujarat & Maharashtra",
    estimatedCost: 108000,
    expenditure: 69120,
    status: "UNDER_IMPLEMENTATION",
    progress: 64,
    startDate: "Sep 2017",
    expectedCompletion: "Aug 2027",
    image: "/images/projects/rail.jpg",
    description: "India's flagship high-speed rail corridor connecting commercial hubs Mumbai and Ahmedabad with 320 km/h Shinkansen bullet train technology.",
    highlights: [
      "508 km total length with 12 world-class terminal stations",
      "21 km undersea tunnel in Thane Creek",
      "Reduces travel time between Mumbai and Ahmedabad from 7 hours to 2 hours",
      "Earthquake early-detection seismometer system",
    ],
    aiRiskScore: "Low",
  },
  {
    id: "proj-3",
    projectId: "BMRCL-PH4-2023",
    projectName: "Metro Rail Project",
    category: "Urban",
    sector: "Urban Infrastructure",
    ministry: "Ministry of Housing & Urban Affairs",
    department: "Urban Transit Division",
    agency: "Bangalore Metro Rail Corporation Ltd (BMRCL)",
    location: "Bengaluru Metropolitan Region",
    state: "Karnataka",
    estimatedCost: 30500,
    expenditure: 24705,
    status: "ON_TRACK",
    progress: 81,
    startDate: "Jan 2020",
    expectedCompletion: "Dec 2025",
    image: "/images/projects/metro.jpg",
    description: "Multi-corridor driverless metro transit line linking the technology corridors of Whitefield, Electronic City, and Kempegowda International Airport.",
    highlights: [
      "Communication-Based Train Control (CBTC) signaling",
      "100% solar powered elevated transit stations",
      "Integration with Suburban rail and bus terminals",
      "Average daily expected ridership: 1.5 million commuters",
    ],
    aiRiskScore: "Optimal",
  },
  {
    id: "proj-4",
    projectId: "MNRE-UMSP-2022",
    projectName: "Renewable Energy Park",
    category: "Energy",
    sector: "Energy",
    ministry: "Ministry of New & Renewable Energy",
    department: "Solar Energy Mission",
    agency: "Solar Energy Corporation of India (SECI)",
    location: "Khavda & Rewa",
    state: "Gujarat",
    estimatedCost: 18200,
    expenditure: 10556,
    status: "UNDER_IMPLEMENTATION",
    progress: 58,
    startDate: "Oct 2021",
    expectedCompletion: "Mar 2027",
    image: "/images/projects/solar.jpg",
    description: "Massive 30 GW hybrid renewable energy park combining high-efficiency bifacial solar photovoltaic arrays and high-capacity wind turbine systems.",
    highlights: [
      "Offsetting 50 million tonnes of CO2 emissions annually",
      "Integrated battery energy storage system (BESS)",
      "High-voltage direct current (HVDC) transmission link to national grid",
      "Automated robotic dry-cleaning for solar modules to conserve water",
    ],
    aiRiskScore: "Low",
  },
  {
    id: "proj-5",
    projectId: "JS-NWM-POL-2020",
    projectName: "National Water Mission",
    category: "Water",
    sector: "Water & Sanitation",
    ministry: "Ministry of Jal Shakti",
    department: "Department of Water Resources",
    agency: "Polavaram Project Authority",
    location: "Eluru & Alluri Sitharama Raju districts",
    state: "Andhra Pradesh",
    estimatedCost: 45000,
    expenditure: 29700,
    status: "ON_TRACK",
    progress: 66,
    startDate: "Jun 2018",
    expectedCompletion: "Jun 2026",
    image: "/images/projects/water.jpg",
    description: "Monumental irrigation, drinking water, and hydroelectric infrastructure project across the Godavari River to irrigate 7.2 lakh acres.",
    highlights: [
      "Earth-cum-rockfill dam spanning 2,450 meters",
      "960 MW hydro-power generation facility",
      "Supplies 23.4 TMC drinking water to Visakhapatnam municipal region",
      "Interlinking Godavari-Krishna river basin networks",
    ],
    aiRiskScore: "Moderate",
  },
  {
    id: "proj-6",
    projectId: "NR-USBRL-CHNB-2017",
    projectName: "Chenab Railway Bridge & USBRL",
    category: "Railways",
    sector: "Railways",
    ministry: "Ministry of Railways",
    department: "Northern Railway Construction",
    agency: "Konkan Railway Corporation Ltd (KRCL)",
    location: "Reasi, Jammu & Kashmir",
    state: "Jammu & Kashmir",
    estimatedCost: 28000,
    expenditure: 26600,
    status: "COMPLETED",
    progress: 95,
    startDate: "Jul 2017",
    expectedCompletion: "Completed (Operational Testing)",
    image: "/images/projects/bridge.jpg",
    description: "Engineering marvel towering 359 meters above the Chenab River gorge, connecting the Kashmir Valley with the rest of the Indian railway network.",
    highlights: [
      "Steel arch spanning 467 meters, higher than the Eiffel Tower",
      "Engineered to withstand earthquake intensity up to Zone V",
      "Equipped with online structural health and wind monitoring sensors",
      "All-weather heavy freight and high-speed passenger train capable",
    ],
    aiRiskScore: "Optimal",
  },
];

export const EXPLORE_ALL_PROJECTS: PublicProject[] = [
  ...FEATURED_PROJECTS,
  {
    id: "proj-7",
    projectId: "DFCCIL-EDFC-2019",
    projectName: "Eastern Dedicated Freight Corridor",
    category: "Railways",
    sector: "Railways",
    ministry: "Ministry of Railways",
    department: "Railway Logistics",
    agency: "Dedicated Freight Corridor Corporation (DFCCIL)",
    location: "Ludhiana to Dankuni (1,875 km)",
    state: "Multiple States",
    estimatedCost: 51459,
    expenditure: 46313,
    status: "COMPLETED",
    progress: 90,
    startDate: "Jan 2016",
    expectedCompletion: "Completed",
    image: "/images/projects/rail.jpg",
    description: "High-axle-load freight corridor reducing cargo transit time across the northern and eastern industrial belt by 60%.",
    highlights: ["Doubles average freight train speed to 75 km/h", "Automated electric traction and computerized dispatch", "Seamless connectivity to deep-sea ports"],
    aiRiskScore: "Optimal",
  },
  {
    id: "proj-8",
    projectId: "MORTH-BMP-2020",
    projectName: "Bharatmala Pariyojana Economic Corridors",
    category: "Transport",
    sector: "Roads & Highways",
    ministry: "Ministry of Road Transport & Highways",
    department: "National Highway Development",
    agency: "NHAI / NHIDCL",
    location: "National Multi-Modal Corridors",
    state: "Pan-India",
    estimatedCost: 535000,
    expenditure: 406600,
    status: "ON_TRACK",
    progress: 76,
    startDate: "Oct 2017",
    expectedCompletion: "Mar 2027",
    image: "/images/projects/expressway.jpg",
    description: "National umbrella highway project developing 34,800 km of high-speed economic corridors, border connectivity, and coastal roads.",
    highlights: ["Connects 550 district headquarters across India", "Multi-modal logistics park integration", "Emergency aircraft landing strips on expressways"],
    aiRiskScore: "Low",
  },
  {
    id: "proj-9",
    projectId: "MOP-GEC-2021",
    projectName: "Green Energy Corridor Phase-II",
    category: "Energy",
    sector: "Energy",
    ministry: "Ministry of Power",
    department: "Transmission Division",
    agency: "Power Grid Corporation of India Ltd",
    location: "Gujarat, Rajasthan, MP, TN, Karnataka",
    state: "Multiple States",
    estimatedCost: 12031,
    expenditure: 8421,
    status: "ON_TRACK",
    progress: 70,
    startDate: "Apr 2022",
    expectedCompletion: "Dec 2026",
    image: "/images/projects/solar.jpg",
    description: "Inter-state transmission system evacuation of 20,000 MW renewable power from key solar and wind zones to national demand centres.",
    highlights: ["10,750 ckm of ultra-high voltage transmission lines", "27,500 MVA transformation capacity", "Smart grid real-time stability controllers"],
    aiRiskScore: "Optimal",
  },
  {
    id: "proj-10",
    projectId: "MOWR-JJM-2020",
    projectName: "Jal Jeevan Mission Har Ghar Jal",
    category: "Water",
    sector: "Water & Sanitation",
    ministry: "Ministry of Jal Shakti",
    department: "Drinking Water & Sanitation",
    agency: "National Jal Jeevan Mission",
    location: "Rural India Nationwide",
    state: "Pan-India",
    estimatedCost: 360000,
    expenditure: 288000,
    status: "ON_TRACK",
    progress: 80,
    startDate: "Aug 2019",
    expectedCompletion: "Mar 2026",
    image: "/images/projects/water.jpg",
    description: "Providing functional household tap connection (FHTC) with clean potable water (55 lpcd) to every rural household across India.",
    highlights: ["Over 15 Crore rural households provided tap water", "IoT-based flow and water quality monitoring sensors in 20,000+ villages", "Community-led water management committees"],
    aiRiskScore: "Low",
  },
  {
    id: "proj-11",
    projectId: "AAI-NMI-2021",
    projectName: "Navi Mumbai International Airport (NMIA)",
    category: "Aviation",
    sector: "Airports",
    ministry: "Ministry of Civil Aviation",
    department: "Airport Infrastructure",
    agency: "CIDCO / Adani Airports",
    location: "Navi Mumbai",
    state: "Maharashtra",
    estimatedCost: 19646,
    expenditure: 14734,
    status: "UNDER_IMPLEMENTATION",
    progress: 75,
    startDate: "Aug 2018",
    expectedCompletion: "Dec 2025",
    image: "/images/projects/metro.jpg",
    description: "State-of-the-art greenfield international airport with dual independent parallel runways, capable of handling 90 million passengers annually.",
    highlights: ["100% green energy powered airport", "Direct water taxi and express metro connectivity", "High-speed automated baggage handling system"],
    aiRiskScore: "Low",
  },
  {
    id: "proj-12",
    projectId: "MEITY-BBN-2022",
    projectName: "BharatNet Phase-III Digital Backbone",
    category: "Digital",
    sector: "Digital Infrastructure",
    ministry: "Ministry of Communications",
    department: "Department of Telecommunications",
    agency: "Bharat Broadband Network Ltd (BBNL)",
    location: "2.5 Lakh Gram Panchayats",
    state: "Pan-India",
    estimatedCost: 139579,
    expenditure: 90726,
    status: "UNDER_IMPLEMENTATION",
    progress: 65,
    startDate: "Jan 2021",
    expectedCompletion: "Aug 2026",
    image: "/images/projects/expressway.jpg",
    description: "World's largest rural broadband optical fibre connectivity initiative bridging the digital divide for 2,50,000 village councils.",
    highlights: ["Over 6,50,000 km optical fibre laid", "Empowering telemedicine, digital agriculture, and rural e-governance", "Gigabit capability with ring-topology fault recovery"],
    aiRiskScore: "Moderate",
  },
];

export const PUBLIC_MINISTRIES = [
  "All Ministries",
  "Ministry of Road Transport & Highways",
  "Ministry of Railways",
  "Ministry of Housing & Urban Affairs",
  "Ministry of New & Renewable Energy",
  "Ministry of Jal Shakti",
  "Ministry of Power",
  "Ministry of Civil Aviation",
  "Ministry of Communications",
];

export const PUBLIC_SECTORS = [
  "All Sectors",
  "Roads & Highways",
  "Railways",
  "Urban Infrastructure",
  "Energy",
  "Water & Sanitation",
  "Airports",
  "Digital Infrastructure",
];

export const PUBLIC_STATES = [
  "All States/UTs",
  "Pan-India",
  "Multiple States",
  "Maharashtra",
  "Gujarat",
  "Karnataka",
  "Delhi / NCR",
  "Andhra Pradesh",
  "Madhya Pradesh",
  "Jammu & Kashmir",
  "Uttar Pradesh",
  "Tamil Nadu",
];

export const PUBLIC_NEWS = [
  {
    id: "news-1",
    date: "04 Sep 2026",
    ministry: "Ministry of Road Transport & Highways",
    title: "Delhi-Mumbai Expressway Section 3 Reaches 90% Structural Completion",
    snippet: "Green corridor automated monitoring confirms bridge works across Chambal river achieved zero schedule variance this quarter.",
    tag: "Milestone",
  },
  {
    id: "news-2",
    date: "28 Aug 2026",
    ministry: "Cabinet Committee on Economic Affairs (CCEA)",
    title: "Cabinet Approves ₹ 34,000 Cr Additional Allocation for Dedicated Freight Corridors",
    snippet: "Funds earmarked for multimodal logistics hubs and solar traction power infrastructure across 12 high-density industrial routes.",
    tag: "Cabinet Sanction",
  },
  {
    id: "news-3",
    date: "15 Aug 2026",
    ministry: "Ministry of Railways",
    title: "Vande Bharat Sleeper Trains Inaugurate Operations on USBRL Section",
    snippet: "Connecting Srinagar to New Delhi with all-weather high speed travel across the Chenab Arch Bridge engineering feat.",
    tag: "Commissioning",
  },
  {
    id: "news-4",
    date: "02 Aug 2026",
    ministry: "Ministry of Jal Shakti",
    title: "Polavaram Project Spillway Gates Complete Automated Hydrodynamic Testing",
    snippet: "State-of-the-art telemetry and SCADA systems successfully pass flood simulation protocols at full reservoir capacity.",
    tag: "Technical Audit",
  },
];
